// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV-m_7Ww5CFYkMEqPWGARnLpjuzBr6GQ0',
    appId: '1:295433960656:web:1938c422133a51783032d5',
    messagingSenderId: '295433960656',
    projectId: 'devmob-supportclient-5d28b',
    authDomain: 'devmob-supportclient-5d28b.firebaseapp.com',
    storageBucket: 'devmob-supportclient-5d28b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEFwmy8x_D1ZeHnyO2k0in1445RfIpOtY',
    appId: '1:295433960656:android:7d1b07fded9919b23032d5',
    messagingSenderId: '295433960656',
    projectId: 'devmob-supportclient-5d28b',
    storageBucket: 'devmob-supportclient-5d28b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJSwWNgNik8vc6x6W5FvAAgoh_Qu03fWE',
    appId: '1:295433960656:ios:3dd89041a01cce493032d5',
    messagingSenderId: '295433960656',
    projectId: 'devmob-supportclient-5d28b',
    storageBucket: 'devmob-supportclient-5d28b.firebasestorage.app',
    iosBundleId: 'com.example.devmobSupportclient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJSwWNgNik8vc6x6W5FvAAgoh_Qu03fWE',
    appId: '1:295433960656:ios:3dd89041a01cce493032d5',
    messagingSenderId: '295433960656',
    projectId: 'devmob-supportclient-5d28b',
    storageBucket: 'devmob-supportclient-5d28b.firebasestorage.app',
    iosBundleId: 'com.example.devmobSupportclient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDV-m_7Ww5CFYkMEqPWGARnLpjuzBr6GQ0',
    appId: '1:295433960656:web:3f99e53e7e27e8423032d5',
    messagingSenderId: '295433960656',
    projectId: 'devmob-supportclient-5d28b',
    authDomain: 'devmob-supportclient-5d28b.firebaseapp.com',
    storageBucket: 'devmob-supportclient-5d28b.firebasestorage.app',
  );
}
